# Generated by Django 5.0.1 on 2024-02-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=1000)),
                ('findings', models.CharField(max_length=1000)),
                ('doi', models.CharField(max_length=100)),
                ('references', models.CharField(max_length=1000)),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.studytype')),
            ],
        ),
    ]
