# Generated by Django 5.0.1 on 2024-02-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0002_organ_tissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=50)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('genome_size', models.IntegerField()),
                ('url', models.URLField()),
                ('build_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tissue',
            old_name='organ_id',
            new_name='organ',
        ),
        migrations.CreateModel(
            name='CancertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('reference_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.referencegenome')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.patient')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.tissue')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.sampletype')),
            ],
        ),
        migrations.CreateModel(
            name='SNP_Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.gene')),
                ('molecular_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.moleculeprofile')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.sample')),
            ],
        ),
        migrations.CreateModel(
            name='StudySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.cancerttype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.sample')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variation.study')),
            ],
        ),
    ]
