# Generated by Django 5.0.1 on 2024-02-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0003_gene_moleculeprofile_patient_referencegenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='abstract',
            field=models.CharField(max_length=2000),
        ),
    ]
