# Generated by Django 5.0.1 on 2024-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0004_alter_study_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='references',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
