# Generated by Django 5.0.1 on 2024-02-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0005_alter_study_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tissue',
            name='organ',
        ),
    ]
